version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8000:80"
    depends_on: # 追加
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    build: ./docker/php
    volumes:
     - .:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    #command: --default-authentication-plugin=mysql_native_password
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: yamaneco
      MYSQL_PASSWORD: yamaneco
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:



